### PR TITLE
Added COMP token on Optimism

### PR DESCRIPTION
**Pull request by EviLord032**
### Add COMP Token on Optimism
Website: https://compound.finance/
Description: Compound III is an EVM compatible protocol that enables supplying of crypto assets as collateral in order to borrow the base asset. Accounts can also earn interest by supplying the base asset to the protocol.
Twitter: [@compgovernance](https://twitter.com/compgovernance)
Contracts:

Ethereum: https://etherscan.io/token/0xc00e94Cb662C3520282E6f5717214004A7f26888
Optimism: https://optimistic.etherscan.io/token/0x7e7d4467112689329f7E06571eD0E8CbAd4910eE

### CODE REVIEW

**Comment by dmitriy-woof-software** [comment]
Hey, @peteredebs. Please, can you review it? Thanks.

**Comment by dmitriy-woof-software** [comment]
Hey, @njokuScript. Please, can you review it? Thanks.

**Comment by EviLord032** [comment]
Hey, @njokuScript. Please, can you review it? Thanks.

**Comment by njokuScript** [comment]
> Hey, @njokuScript. Please, can you review it? Thanks.

need some form of verification

**Comment by dmitriy-woof-software** [comment]
Hey @njokuScript. May such verification work?

Here you can see all the deployed COMP tokens between the chains - https://docs.compound.finance/

Mainnet COMP
Снимок экрана 2024-05-31 в 22 00 55

Optimism COMP
Снимок экрана 2024-05-31 в 22 01 29

Here I created PR with OP deployment which was merged

**Comment by dmitriy-woof-software** [comment]
Currently, the Compound is run by DAO. Let us know how we can proof it via DAO.

**Comment by dmitriy-woof-software** [comment]
[AlphaGrowth](https://alphagrowth.io/) has received a big grant for the Compound growth program, so they could DM you if needed.

DAO Grant proposal - https://compound.finance/governance/proposals/251

**Pull request merged**
