### PR TITLE
chore: update BITBOT token address

### PR DESCRIPTION
**Pull request by xwlabs99**
Updates new token addresses
ETH: https://etherscan.io/address/0xf241FD6fB9E46F17BA816D4463A2447F3d477Be0#code
Base: https://basescan.org/address/0x8BfB09521EBc971C493FceF170B5A5f169aB54fA#code

### CODE REVIEW

**Comment by xwlabs99** [comment]
@njokuScript Hi! Soryy for bother you, it is an urgent but small change. 
Could u pls merge it in advance? Thank u!

**Comment by njokuScript** [comment]
> @njokuScript Hi! Sorry to bother you, it is an urgent but small change. Could u pls merge it in advance? Thank u!

can you please send a tweet or dm supermigrate on X to verify?

**Comment by xwlabs99** [comment]
> > @njokuScript Hi! Sorry to bother you, it is an urgent but small change. Could u pls merge it in advance? Thank u!
> 
> can you please send a tweet or dm supermigrate on X to verify?

Okay just sent with account @Official_BitBot. Pls check
telegram-cloud-photo-size-5-6174771402700339970-y

**Comment by njokuScript** [comment]
> > > @njokuScript Hi! Sorry to bother you, it is an urgent but small change. Could u pls merge it in advance? Thank u!
> > 
> > 
> > can you please send a tweet or dm supermigrate on X to verify?
> 
> Okay just sent with account @Official_BitBot. Pls check telegram-cloud-photo-size-5-6174771402700339970-y

send it to https://x.com/supermigrate

**Comment by xwlabs99** [comment]
> > > > @njokuScript Hi! Sorry to bother you, it is an urgent but small change. Could u pls merge it in advance? Thank u!
> > > 
> > > 
> > > can you please send a tweet or dm supermigrate on X to verify?
> > 
> > 
> > Okay just sent with account @Official_BitBot. Pls check telegram-cloud-photo-size-5-6174771402700339970-y
> 
> send it to https://x.com/supermigrate
Done.
telegram-cloud-photo-size-5-6174771402700339977-y

**Pull request merged**
